# Generated by Django 4.2.5 on 2023-09-10 16:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="airport",
            options={"ordering": ("closest_big_city",)},
        ),
        migrations.AlterModelOptions(
            name="crew",
            options={"ordering": ("first_name", "last_name")},
        ),
    ]
