# Generated by Django 4.2.5 on 2023-09-30 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0002_alter_airport_options_alter_crew_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrewOccupation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="crew",
            name="experience_years",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name="crew",
            name="occupation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="airport.crewoccupation",
            ),
            preserve_default=False,
        ),
    ]
