# Generated by Django 4.2.5 on 2023-09-10 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("flight", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flight",
            options={"ordering": ("-departure_time",)},
        ),
        migrations.AlterModelOptions(
            name="route",
            options={"ordering": ("id",)},
        ),
        migrations.AddField(
            model_name="flight",
            name="arrival_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="flight",
            name="departure_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
