# Generated by Django 4.2.5 on 2023-09-10 16:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airplane", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="airplane",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="airplanetype",
            options={"ordering": ("name",)},
        ),
    ]
