# Generated by Django 4.2.5 on 2023-09-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airplane", "0002_alter_airplane_options_alter_airplanetype_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="seats_in_row",
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
